/**
 * todos los textos de la app. español de costa rica, voseo y humor seco, con ortografía normal:
 * mayúscula al inicio y en nombres propios, tildes, signos de apertura y "…" en vez de "...".
 * si algo se dice en dos pantallas, se dice desde aquí.
 */
export const copy = {
  app: {
    name: "¿Quién me tocó?",
    tagline: "Amigo secreto sin pagar por una app tan simple.",
    by: "Hecho por ear.dev",
  },

  auth: {
    enter: "Entrar",
    enterWith: "Entrá con Google o Apple.",
    google: "Continuar con Google",
    apple: "Continuar con Apple",
    leaving: "Saliendo…",
    logout: "Salir",
    connecting: "Conectando…",
    needLogin: "Para seguir tenés que entrar.",
    callbackWorking: "Un momento, estamos abriendo la puerta…",
    callbackError: "No pudimos entrar. Probá de nuevo.",
    deviceApproval: {
      title: "Este teléfono es nuevo para nosotros",
      body: "Te mandamos un correo para confirmar que sos vos. Abrilo y volvé aquí.",
      resend: "Mandar el correo otra vez",
    },
  },

  home: {
    sub: "Organizá el amigo secreto, repartí los nombres sin que nadie vea y revelá todo el día del intercambio.",
    create: "Creá un grupo",
    yourGroups: "Tus grupos",
    noGroups: "Todavía no estás en ningún grupo. Creá uno o pedí el link.",
    archived: "Archivados",
    adminBadge: "Lo organizás vos",
    install: "Agregame a tu pantalla",
  },

  status: {
    progress: "En qué va el grupo",
    open: "Apuntándose",
    closed: "Listos",
    drawRequested: "Sorteando…",
    drawn: "Sorteado",
    revealRequested: "Revelando…",
    revealed: "Revelado",
    archived: "Archivado",
  },

  create: {
    title: "Nuevo grupo",
    repeatTitle: "Repetir el próximo año",
    name: "Nombre del grupo",
    namePlaceholder: "Navidad familia Agüero",
    when: "Fecha y hora del intercambio",
    place: "Lugar",
    placePlaceholder: "Casa de la abuela",
    budgetMax: "Presupuesto máximo",
    budgetHint: "En colones. Se vale redondear.",
    expected: "¿Cuántos son?",
    expectedHint: "Contá a todos, también a los que no van a entrar a la app.",
    rules: "Reglas (opcional)",
    rulesPlaceholder: "Nada de calcetines. Ni vales. Ni calcetines con vales.",
    submit: "Crear grupo",
    submitting: "Creando…",
    avoidPrevious: "Que no te toque la misma persona del año pasado",
    avoidPreviousOn: "La opción «Que no te toque la misma persona del año pasado» viene activada. La podés apagar en el panel.",
    created: "Listo. Ahora compartí el link.",
    errors: {
      name: "Ponele un nombre.",
      date: "La fecha tiene que ser en el futuro.",
      budget: "Poné un presupuesto.",
      expected: "Mínimo 3 personas. Si no, no hay secreto.",
    },
  },

  invite: {
    title: (group: string) => `Te invitaron a ${group}`,
    sub: "Entrá, decinos cómo te llamás y qué querés que te regalen.",
    joinedAlready: "Ya estás adentro.",
    closed: "Las inscripciones ya cerraron. Hablá con quien organiza.",
    full: "Ya están todos. Si falta alguien, hablá con quien organiza.",
    notFound: "Ese link no existe o ya no sirve.",
    badInvite: "El código de invitación no es válido. Pedí el link otra vez.",
    name: "Nombre o apodo",
    namePlaceholder: "Como te dicen en la casa",
    email: "Correo",
    emailHint: "Para avisarte quién te tocó. Se borra después del intercambio.",
    emailInvalid: "Ese correo no se ve bien.",
    submit: "Apuntarme",
    submitting: "Apuntándote…",
    done: "Listo, estás adentro. Shh.",
    whatsapp: "Compartir por WhatsApp",
    copyLink: "Copiar link",
    copied: "Copiado",
  },

  wishlist: {
    title: "¿Qué querés que te regalen?",
    mine: "Mi wishlist",
    theirs: (name: string) => `La wishlist de ${name}`,
    ideas: "Ideas de regalo",
    ideasPlaceholder: "Libros, café, una planta que no se muera",
    sizes: "Tallas",
    sizesPlaceholder: "Camisa M, zapatos 40",
    links: "Links (opcional)",
    linksPlaceholder: "Uno por línea",
    save: "Guardar",
    saving: "Guardando…",
    saved: "Guardado",
    empty: "Todavía no ha puesto nada. Paciencia.",
    edit: "Editar",
    cancel: "Cancelar",
    updatedLive: "Siempre actualizada",
  },

  admin: {
    title: "Tu panel",
    onlyAdmin: "Este panel es solo para quien organiza.",
    archive: "Archivar",
    archiveHint: "Se apaga. Deja de verse en la lista y queda como archivado.",
    unarchive: "Volver a prender",
    archived: "Este grupo está archivado.",
    registered: "Ya se apuntaron",
    missing: (n: number) =>
      n === 0 ? "Ya están todos." : n === 1 ? "Falta 1 por apuntarse." : `Faltan ${n} por apuntarse.`,
    expected: (have: number, want: number) => `${have} de ${want}`,
    closeRegistrations: "Cerrar inscripciones",
    reopenRegistrations: "Abrir inscripciones",
    changeExpected: "Cambiar cuántos son",
    ghostsTitle: "Sin cuenta",
    addGhost: "Agregar a alguien sin cuenta",
    ghostName: "Nombre",
    ghostPlaceholder: "La abuela",
    ghostHint: "Para la abuela y para quien no va a entrar a la app. Vos le pasás el resultado.",
    ghostAdd: "Agregar",
    ghostWishlist: "Llenarle la wishlist",
    remove: "Quitar",
    removePerson: (name: string) => `Quitar a ${name}`,
    exclusions: "Exclusiones",
    exclusionsHint: "Pares que no se pueden tocar entre sí. Por ejemplo, parejas.",
    exclusionsAdd: "Agregar exclusión",
    exclusionsEmpty: "Sin exclusiones. Todos contra todos.",
    exclusionsSave: "Guardar exclusiones",
    exclusionA: "Primera persona",
    exclusionB: "Segunda persona",
    removeExclusion: (a: string, b: string) => `Quitar la exclusión entre ${a} y ${b}`,
    infeasible: "Con estas reglas no sale el sorteo. Quitá alguna exclusión.",
    draw: "Hacer sorteo",
    drawDisabled: "El botón se activa cuando estén todos.",
    drawConfirm: "Una vez hecho, queda fijo. ¿Dale?",
    drawing: "Mezclando los papelitos…",
    drawn: "Sorteo hecho. Nadie sabe nada, ni vos.",
    emails: (sent: number, total: number) => `Correos enviados: ${sent} de ${total}`,
    emailsLabel: "Correos",
    emailStatus: {
      sent: "Enviado",
      pending: "Pendiente",
      tomorrow: "Sale mañana",
      failed: "No salió",
    },
    emailsRetry: "Reintentar",
    emailsTomorrow: "Resend llegó al tope de hoy. Mañana seguimos.",
    ghostLinks: "Links privados",
    ghostLinksHint: "Copiá el link y pasáselo por WhatsApp. Vos no ves el resultado.",
    copyGhostLink: (name: string) => `Copiar link de ${name}`,
    ghostOpened: "Ya lo abrió",
    showQr: "Mostrar QR",
    qrTitle: (name: string) => `El papelito de ${name}`,
    qrAlt: (name: string) => `Código QR del papelito de ${name}`,
    reveal: "Revelar todo",
    revealHint: "Solo el día del intercambio. Nadie más tiene este botón.",
    revealTooEarly: (when: string) => `Se habilita el ${when}.`,
    revealing: "Destapando…",
    revealed: "Ya está todo revelado.",
    share: "Compartir link de invitación",
    calendar: "Agregar al calendario",
    iAlsoPlay: "Yo también juego",
  },

  participant: {
    waiting: "Todavía no hay sorteo. Mientras, podés editar tu wishlist.",
    missing: (n: number) =>
      n === 1 ? "Falta 1 por apuntarse." : `Faltan ${n} por apuntarse.`,
    drawing: "Están mezclando los papelitos…",
    reveal: "¿Quién me tocó?",
    tap: "Tocá para ver",
    youGot: "Te tocó…",
    shh: "Shh, no le digás a nadie.",
    verifiedLocal: "Tu papelito coincide con lo sellado.",
    movingKey: "Estamos pasando tu papelito a este teléfono…",
    movingKeyHint: "Tarda un momento. No cerrés la app.",
    noKeyYet: "Este teléfono no tiene tu llave todavía.",
    moveKey: "Traer mi papelito aquí",
    notInGroup: "No estás en este grupo.",
    budget: (min: string, max: string) => `Presupuesto: ${min} a ${max}`,
    when: "Cuándo",
    where: "Dónde",
    budgetLabel: "Presupuesto",
    rulesLabel: "Reglas",
  },

  ghost: {
    title: "Tu papelito",
    hello: (name: string) => `Hola, ${name}. Este es tu papelito.`,
    used: "Este link ya se abrió en otro teléfono. Pedile otro a quien organiza.",
    expired: "Este link ya venció.",
    invalid: "Este link no existe.",
    loading: "Abriendo tu papelito…",
  },

  finalReveal: {
    title: "Llegó el día.",
    sub: "¿Quién le regaló a quién?",
    start: "Destapar",
    next: "Siguiente",
    auto: "Automático",
    pause: "Pausar",
    gaveTo: "le regaló a",
    done: "Eso fue todo. Gracias por jugar.",
    createYourOwn: "Creá tu propio grupo",
    repeatNextYear: "Repetir el próximo año",
    verify: "Verificá que el sorteo fue justo",
    notYet: "Todavía no se ha revelado. El día del intercambio, quien organiza destapa todo.",
  },

  verify: {
    title: "Verificá que el sorteo fue justo",
    intro:
      "Cuando se hizo el sorteo, cada papelito quedó sellado en una cadena pública antes de que nadie supiera nada. Al revelar, se abrieron los sellos y comprobamos que coinciden.",
    sealedAt: (when: string) => `Sellado el ${when}`,
    revealedAt: (when: string) => `Revelado el ${when}`,
    checking: "Comprobando sellos…",
    ok: "Todo coincide. El sorteo fue justo.",
    fail: "Algo no coincide. Avisale a quien organiza.",
    pending: "Todavía no se ha revelado, así que no hay nada que comparar. Los sellos ya están puestos.",
    seals: (n: number) => `${n} sellos`,
    explorerDraw: "Ver el sorteo en Starknet",
    explorerReveal: "Ver la revelación en Starknet",
    explorerContract: "Ver el contrato en Starknet",
    howTitle: "¿Cómo funciona?",
    how: [
      "El día del sorteo se guardó un sello por persona: un número que depende de a quién le tocó y de un secreto.",
      "Sin el secreto, el sello no dice nada. Por eso nadie pudo ver nada antes.",
      "Al revelar, se publicaron los secretos y cualquiera puede recalcular los sellos y ver que son los mismos.",
    ],
  },

  pay: {
    title: "Esto no cuesta nada.",
    body: "Si te sirvió, pagame con un follow y una historia.",
    follow: "Seguir a @ear.dev",
    story: "Subir una historia",
    storyHint: "Subila a tu historia y etiquetá a @ear.dev.",
    storyFallback: "Descargamos la imagen y copiamos @ear.dev. Ahora subila a tu historia.",
    storyShareText: (handle: string) => `Gracias, ${handle}`,
    thanks: "Gracias, en serio.",
  },

  calendar: {
    add: "Agregar al calendario",
    google: "Google Calendar",
    ics: "Apple u otro calendario",
    summary: (group: string) => `Intercambio: ${group}`,
  },

  pwa: {
    install: "Agregame a tu pantalla",
    installBody: "Así se abre como una app, sin barras del navegador.",
    installAndroid: "Instalar",
    iosTitle: "En iPhone",
    iosSteps: ["Tocá «Compartir».", "Después, tocá «Agregar a inicio»."],
    androidSteps: "Abrí el menú del navegador y tocá «Instalar app».",
    later: "Después",
    offlineTitle: "Sin internet",
    offlineBody: "Los papelitos están en la nube, no en este teléfono. Volvé cuando tengás señal.",
    retry: "Reintentar",
  },

  common: {
    back: "Volver",
    close: "Cerrar",
    loading: "Cargando…",
    refresh: "Actualizar",
    error: "Algo salió mal. Probá de nuevo.",
    errorRejected: "Cancelaste la operación.",
    errorDeviceApproval: "Este dispositivo todavía no está autorizado. Revisá tu correo.",
    errorWalletDeploy: "Preparando tu cuenta…",
    errorPaymaster: "El sistema de pagos no está disponible ahora. Intentá de nuevo en unos minutos.",
    errorNetwork: "No pudimos conectar con la red. Revisá tu conexión.",
    txPending: "Guardando en la cadena…",
    txDone: "Listo",
    people: (n: number) => (n === 1 ? "1 persona" : `${n} personas`),
    you: "Vos",
    yes: "Dale",
    no: "Mejor no",
    notFound: "Esto no existe.",
  },
} as const;

export type Copy = typeof copy;
