/**
 * todos los textos de la app. español de costa rica, voseo, minúsculas, humor seco.
 * si algo se dice en dos pantallas, se dice desde aquí.
 */
export const copy = {
  app: {
    name: "¿quién me tocó?",
    tagline: "amigo secreto sin pagar por una app tan simple",
    by: "hecho por ear.dev",
  },

  auth: {
    enter: "entrar",
    enterWith: "entrá con google o apple",
    leaving: "saliendo...",
    logout: "salir",
    connecting: "conectando...",
    needLogin: "para seguir tenés que entrar",
    callbackWorking: "un momento, estamos abriendo la puerta...",
    callbackError: "no pudimos entrar. probá de nuevo.",
    deviceApproval: {
      title: "este teléfono es nuevo para nosotros",
      body: "te mandamos un correo para confirmar que sos vos. abrilo y volvé aquí.",
      resend: "mandar el correo otra vez",
    },
  },

  home: {
    heroA: "¿quién",
    heroB: "me tocó?",
    sub: "organizá el amigo secreto, repartí los nombres sin que nadie vea, y revelá todo el día del intercambio.",
    create: "creá un grupo",
    yourGroups: "tus grupos",
    noGroups: "todavía no estás en ningún grupo. creá uno o pedí el link.",
    adminBadge: "lo organizás vos",
    install: "agregame a tu pantalla",
  },

  status: {
    open: "apuntándose",
    closed: "inscripciones cerradas",
    drawRequested: "sorteando...",
    drawn: "sorteado",
    revealRequested: "revelando...",
    revealed: "revelado",
  },

  create: {
    title: "nuevo grupo",
    repeatTitle: "repetir el próximo año",
    name: "nombre del grupo",
    namePlaceholder: "navidad familia aguero",
    date: "fecha del intercambio",
    time: "hora",
    place: "lugar",
    placePlaceholder: "casa de la abuela",
    budgetMin: "presupuesto mínimo",
    budgetMax: "presupuesto máximo",
    budgetHint: "en colones. se vale redondear.",
    expected: "¿cuántos son?",
    expectedHint: "contá a todos, también a los que no van a entrar a la app.",
    rules: "reglas (opcional)",
    rulesPlaceholder: "nada de calcetines. ni vales. ni calcetines con vales.",
    submit: "crear grupo",
    submitting: "creando...",
    avoidPrevious: "que no te toque la misma persona del año pasado",
    created: "listo. ahora compartí el link.",
    errors: {
      name: "ponele un nombre",
      date: "la fecha tiene que ser en el futuro",
      budget: "el máximo tiene que ser mayor o igual al mínimo",
      expected: "mínimo 3 personas, si no, no hay secreto",
    },
  },

  invite: {
    title: (group: string) => `te invitaron a ${group}`,
    sub: "entrá, decinos cómo te llamás y qué querés que te regalen.",
    joinedAlready: "ya estás adentro.",
    closed: "las inscripciones ya cerraron. hablá con quien organiza.",
    full: "ya están todos. si falta alguien, hablá con quien organiza.",
    notFound: "ese link no existe o ya no sirve.",
    name: "nombre o apodo",
    namePlaceholder: "como te dicen en la casa",
    email: "correo",
    emailHint: "para avisarte quién te tocó. se borra después del intercambio.",
    submit: "apuntarme",
    submitting: "apuntándote...",
    done: "listo, estás adentro. shh.",
    whatsapp: "compartir por whatsapp",
    copyLink: "copiar link",
    copied: "copiado",
  },

  wishlist: {
    title: "¿qué querés que te regalen?",
    mine: "mi wishlist",
    theirs: (name: string) => `la wishlist de ${name}`,
    ideas: "ideas de regalo",
    ideasPlaceholder: "libros, café, una planta que no se muera",
    sizes: "tallas",
    sizesPlaceholder: "camisa m, zapatos 40",
    links: "links (opcional)",
    linksPlaceholder: "uno por línea",
    save: "guardar",
    saving: "guardando...",
    saved: "guardado",
    empty: "todavía no ha puesto nada. paciencia.",
    edit: "editar",
    cancel: "cancelar",
    updatedLive: "siempre actualizada",
  },

  admin: {
    title: "tu panel",
    registered: "ya se apuntaron",
    missing: (n: number) =>
      n === 0 ? "ya están todos" : n === 1 ? "falta 1 por apuntarse" : `faltan ${n} por apuntarse`,
    expected: (have: number, want: number) => `${have} de ${want}`,
    closeRegistrations: "cerrar inscripciones",
    reopenRegistrations: "abrir inscripciones",
    changeExpected: "cambiar cuántos son",
    addGhost: "agregar a alguien sin cuenta",
    ghostName: "nombre",
    ghostHint: "para la abuela y para quien no va a hacer login. vos le pasás el resultado.",
    ghostAdd: "agregar",
    ghostWishlist: "llenarle la wishlist",
    remove: "quitar",
    exclusions: "exclusiones",
    exclusionsHint: "pares que no se pueden tocar entre sí. por ejemplo, parejas.",
    exclusionsAdd: "agregar exclusión",
    exclusionsEmpty: "sin exclusiones. todos contra todos.",
    exclusionsSave: "guardar exclusiones",
    infeasible: "con estas reglas no sale el sorteo, quitá alguna exclusión",
    draw: "hacer sorteo",
    drawDisabled: "cuando estén todos, aquí aparece el botón",
    drawConfirm: "una vez hecho, queda fijo. ¿dale?",
    drawing: "mezclando los papelitos...",
    drawn: "sorteo hecho. nadie sabe nada, ni vos.",
    emails: (sent: number, total: number) => `correos enviados: ${sent}/${total}`,
    emailsRetry: "reintentar",
    emailsTomorrow: "resend llegó al tope de hoy. mañana seguimos.",
    ghostLinks: "links privados",
    ghostLinksHint: "copiá el link y pasáselo por whatsapp. vos no ves el resultado.",
    copyGhostLink: (name: string) => `copiar link de ${name}`,
    showQr: "mostrar qr",
    reveal: "revelar todo",
    revealHint: "solo el día del intercambio. nadie más tiene este botón.",
    revealTooEarly: (when: string) => `se habilita ${when}`,
    revealing: "destapando...",
    revealed: "ya está todo revelado.",
    share: "compartir link de invitación",
    calendar: "agregar al calendario",
    iAlsoPlay: "yo también juego",
  },

  participant: {
    waiting: "todavía no hay sorteo. mientras, podés editar tu wishlist.",
    missing: (n: number) =>
      n === 1 ? "falta 1 por apuntarse" : `faltan ${n} por apuntarse`,
    drawing: "están mezclando los papelitos...",
    reveal: "¿quién me tocó?",
    tap: "tocá para ver",
    youGot: "te tocó...",
    shh: "shh, no le digás a nadie",
    verifiedLocal: "tu papelito coincide con lo sellado",
    movingKey: "estamos pasando tu papelito a este teléfono...",
    movingKeyHint: "tarda un momento. no cerrés la app.",
    noKeyYet: "este teléfono no tiene tu llave todavía.",
    moveKey: "traer mi papelito aquí",
    notInGroup: "no estás en este grupo.",
    budget: (min: string, max: string) => `presupuesto: ${min} a ${max}`,
    when: "cuándo",
    where: "dónde",
  },

  ghost: {
    title: "tu papelito",
    used: "este link ya se abrió en otro teléfono. pedile otro a quien organiza.",
    expired: "este link ya venció.",
    invalid: "este link no existe.",
    loading: "abriendo tu papelito...",
  },

  finalReveal: {
    title: "llegó el día.",
    sub: "¿quién le regaló a quién?",
    start: "destapar",
    next: "siguiente",
    gaveTo: "le regaló a",
    done: "eso fue todo. gracias por jugar.",
    createYourOwn: "creá tu propio grupo",
    repeatNextYear: "repetir el próximo año",
    verify: "verificá que el sorteo fue justo",
    notYet: "todavía no se ha revelado. el día del intercambio quien organiza destapa todo.",
  },

  verify: {
    title: "verificá que el sorteo fue justo",
    intro:
      "cuando se hizo el sorteo, cada papelito quedó sellado en una cadena pública antes de que nadie supiera nada. al revelar, se abrieron los sellos y comprobamos que coinciden.",
    sealedAt: (when: string) => `sellado el ${when}`,
    revealedAt: (when: string) => `revelado el ${when}`,
    checking: "comprobando sellos...",
    ok: "todo coincide. el sorteo fue justo.",
    fail: "algo no coincide. avisale a quien organiza.",
    pending: "todavía no se ha revelado, así que no hay nada que comparar. los sellos ya están puestos.",
    seals: (n: number) => `${n} sellos`,
    explorerDraw: "ver el sorteo en starknet",
    explorerReveal: "ver la revelación en starknet",
    howTitle: "¿cómo funciona?",
    how: [
      "el día del sorteo se guardó un sello por persona: un número que depende de a quién le tocó y de un secreto.",
      "sin el secreto, el sello no dice nada. por eso nadie pudo ver nada antes.",
      "al revelar, se publicaron los secretos y cualquiera puede recalcular los sellos y ver que son los mismos.",
    ],
  },

  pay: {
    title: "esto no cuesta nada.",
    body: "si te sirvió, pagame con un follow y una historia.",
    follow: "seguir a @ear.dev",
    story: "subir una historia",
    storyHint: "subila a tu historia y etiquetá a @ear.dev",
    storyFallback: "descargamos la imagen y copiamos @ear.dev. ahora subila a tu historia.",
    thanks: "gracias, en serio.",
  },

  calendar: {
    add: "agregar al calendario",
    google: "google calendar",
    ics: "apple / otro calendario",
    summary: (group: string) => `intercambio: ${group}`,
  },

  pwa: {
    install: "agregame a tu pantalla",
    installBody: "así se abre como una app, sin barras del navegador.",
    installAndroid: "instalar",
    iosTitle: "en iphone",
    iosSteps: ["tocá compartir", "después, agregar a inicio"],
    later: "después",
    offlineTitle: "sin internet",
    offlineBody: "los papelitos están en la nube, no en este teléfono. volvé cuando tengás señal.",
    retry: "reintentar",
  },

  common: {
    back: "volver",
    close: "cerrar",
    loading: "cargando...",
    error: "algo salió mal. probá de nuevo.",
    txPending: "guardando en la cadena...",
    txDone: "listo",
    people: (n: number) => (n === 1 ? "1 persona" : `${n} personas`),
    and: "y",
    you: "vos",
    yes: "dale",
    no: "mejor no",
    notFound: "esto no existe.",
  },
} as const;

export type Copy = typeof copy;
